# Generated by Django 5.2.3 on 2025-06-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
