# Generated by Django 5.2.3 on 2025-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='apellido',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
