# Generated by Django 5.1.7 on 2025-07-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0002_pasajero_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='pasaporte',
            field=models.CharField(max_length=20),
        ),
    ]
