# Generated by Django 5.1.7 on 2025-06-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0003_remove_asiento_estado'),
        ('pasajeros', '0001_initial'),
        ('reservas', '0004_pasajero_usuario'),
        ('vuelos', '0004_alter_vuelo_destino_alter_vuelo_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajeros.pasajero'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('pasajero', 'vuelo'), name='unique_reserva_por_pasajero_y_vuelo'),
        ),
        migrations.DeleteModel(
            name='Pasajero',
        ),
    ]
