# Generated by Django 5.2.3 on 2025-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_pasajero_nacionalidad_remove_pasajero_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
