# Generated by Django 5.2.3 on 2025-07-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_reserva_unique_reserva_por_vuelo_y_asiento_and_more'),
        ('reservas', '0006_reserva_activa'),
    ]

    operations = [
    ]
