# Generated by Django 5.2.3 on 2025-08-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_merge_20250722_1043'),
        ('reservas', '0007_merge_20250723_2054'),
    ]

    operations = [
    ]
