# Generated by Django 5.2.3 on 2025-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
